# Generated by Django 6.0.5 on 2026-05-24 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.CharField(choices=[('low', 'Faible'), ('critical', 'Critique'), ('out', 'Rupture')], max_length=10)),
                ('stock_at_alert', models.IntegerField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Alerte stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('sale', 'Vente'), ('sale_cancel', 'Annulation vente'), ('restock', 'Réapprovisionnement'), ('adjustment', 'Ajustement manuel'), ('loss', 'Perte / Casse'), ('return', 'Retour client'), ('initial', 'Stock initial')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('stock_before', models.IntegerField()),
                ('stock_after', models.IntegerField()),
                ('unit_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
