# Generated by Django 4.2.13 on 2026-08-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("sale", "Vente"),
                    ("sale_cancel", "Annulation vente"),
                    ("restock", "Réapprovisionnement"),
                    ("restock_cancel", "Annulation réappro"),
                    ("adjustment", "Ajustement manuel"),
                    ("loss", "Perte / Casse"),
                    ("return", "Retour client"),
                    ("initial", "Stock initial"),
                ],
                max_length=20,
            ),
        ),
    ]
