# Generated by Django 6.0.5 on 2026-05-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='MICROLOGIS', max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(default='Parakou, Bénin', max_length=100)),
                ('currency', models.CharField(default='FCFA', max_length=10)),
                ('currency_symbol', models.CharField(default='F', max_length=5)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('color_primary', models.CharField(default='#1A2B4A', max_length=7)),
                ('color_accent', models.CharField(default='#2563EB', max_length=7)),
                ('color_success', models.CharField(default='#16A34A', max_length=7)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('critical_stock_threshold', models.PositiveIntegerField(default=2)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('invoice_prefix', models.CharField(default='MICRO', max_length=10)),
                ('invoice_counter', models.PositiveIntegerField(default=1)),
                ('quotation_prefix', models.CharField(default='DEV', max_length=10)),
                ('quotation_counter', models.PositiveIntegerField(default=1)),
                ('restock_prefix', models.CharField(default='REAP', max_length=10)),
                ('restock_counter', models.PositiveIntegerField(default=1)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('footer_invoice_text', models.TextField(default='Merci pour votre confiance !')),
            ],
            options={
                'verbose_name': 'Paramètres magasin',
            },
        ),
    ]
