# Generated by Django 4.2.13 on 2026-08-15 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0001_initial"),
        ("catalog", "0002_alter_product_is_active_alter_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="catalog.category",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="stores.store",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="selling_price",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("store", "parent", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("store", "slug"), ("store", "sku")},
        ),
        migrations.RemoveField(
            model_name="product",
            name="purchase_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="subcategory",
        ),
        migrations.DeleteModel(
            name="SubCategory",
        ),
    ]
