# Generated by Django 4.2.13 on 2026-08-15 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_flush_and_create_default_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="stores.store",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="stores.store",
            ),
        ),
    ]
