# Generated by Django 4.2.13 on 2026-06-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_alter_sale_created_at_alter_sale_sale_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Espèces"),
                    ("mtn", "MTN Mobile Money"),
                    ("moov", "Moov Money"),
                    ("celtiis", "Celtiis Money"),
                    ("card", "Carte bancaire"),
                    ("transfer", "Virement"),
                    ("mixed", "Mixte"),
                ],
                default="cash",
                max_length=15,
            ),
        ),
    ]
