# Generated by Django 4.2.13 on 2026-08-15 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_category_parent_category_store_product_store_and_more"),
        ("sales", "0003_alter_sale_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restock",
            name="total_cost",
        ),
        migrations.RemoveField(
            model_name="restockitem",
            name="unit_cost",
        ),
        migrations.RemoveField(
            model_name="saleitem",
            name="purchase_price",
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sale_items",
                to="catalog.product",
            ),
        ),
    ]
