# Generated by Django 4.2.13 on 2026-08-16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_remove_restock_total_cost_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="discount",
        ),
    ]
